import type { ProjectileDefinitionId } from "../../core/ids";
import { DefinitionRegistry } from "../registry";
import {
  SNIPER_ROUND_PROJECTILE_ID,
  STANDARD_ROUND_PROJECTILE_ID,
} from "../entities/definitions";

export type EnemyAttackAction =
  | "melee-lunge"
  | "projectile-volley"
  | "deploy-barrier"
  | "deploy-mine"
  | "blink-lunge"
  | "support-pulse";

export interface EnemyAttackProfileDefinition {
  readonly id: string;
  readonly action: EnemyAttackAction;
  readonly telegraphMs: number;
  readonly minimumTelegraphMs: number;
  readonly activeMs: number;
  readonly recoveryMs: number;
  readonly cooldownMs: number;
  readonly minimumRange: number;
  readonly maximumRange: number;
  readonly activeMoveSpeed: number;
  readonly projectileDefinitionId: ProjectileDefinitionId | null;
  readonly volleyAnglesRadians: readonly number[];
  readonly deploymentCount: number;
  readonly repeatTelegraphMs: number | null;
}

const degrees = (value: number) => value * Math.PI / 180;

export const enemyAttackProfiles = new DefinitionRegistry<EnemyAttackProfileDefinition>([
  {
    id: "striker-thrust-v1",
    action: "melee-lunge",
    telegraphMs: 563,
    minimumTelegraphMs: 450,
    activeMs: 220,
    recoveryMs: 520,
    cooldownMs: 900,
    minimumRange: 0,
    maximumRange: 4.5,
    activeMoveSpeed: 10,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
  {
    id: "gunner-round-v1",
    action: "projectile-volley",
    telegraphMs: 625,
    minimumTelegraphMs: 500,
    activeMs: 1,
    recoveryMs: 300,
    cooldownMs: 875,
    minimumRange: 3.5,
    maximumRange: 18,
    activeMoveSpeed: 0,
    projectileDefinitionId: STANDARD_ROUND_PROJECTILE_ID,
    volleyAnglesRadians: [0],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
  {
    id: "lancer-charge-v1",
    action: "melee-lunge",
    telegraphMs: 813,
    minimumTelegraphMs: 650,
    activeMs: 520,
    recoveryMs: 850,
    cooldownMs: 1_250,
    minimumRange: 3,
    maximumRange: 18,
    activeMoveSpeed: 18,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
  {
    id: "constructor-barrier-v1",
    action: "deploy-barrier",
    telegraphMs: 700,
    minimumTelegraphMs: 600,
    activeMs: 1,
    recoveryMs: 450,
    cooldownMs: 1_850,
    minimumRange: 4,
    maximumRange: 20,
    activeMoveSpeed: 0,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 1,
    repeatTelegraphMs: null,
  },
  {
    id: "mine-layer-drop-v1",
    action: "deploy-mine",
    telegraphMs: 450,
    minimumTelegraphMs: 400,
    activeMs: 1,
    recoveryMs: 350,
    cooldownMs: 1_600,
    minimumRange: 0,
    maximumRange: 20,
    activeMoveSpeed: 0,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 1,
    repeatTelegraphMs: null,
  },
  {
    id: "sniper-round-v1",
    action: "projectile-volley",
    telegraphMs: 1_125,
    minimumTelegraphMs: 900,
    activeMs: 1,
    recoveryMs: 550,
    cooldownMs: 1_250,
    minimumRange: 6,
    maximumRange: 30,
    activeMoveSpeed: 0,
    projectileDefinitionId: SNIPER_ROUND_PROJECTILE_ID,
    volleyAnglesRadians: [0],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
  {
    id: "vanguard-thrust-v1",
    action: "melee-lunge",
    telegraphMs: 600,
    minimumTelegraphMs: 500,
    activeMs: 260,
    recoveryMs: 650,
    cooldownMs: 1_100,
    minimumRange: 0,
    maximumRange: 4.2,
    activeMoveSpeed: 8,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
  {
    id: "bastion-sweep-v1",
    action: "melee-lunge",
    telegraphMs: 800,
    minimumTelegraphMs: 700,
    activeMs: 340,
    recoveryMs: 800,
    cooldownMs: 1_350,
    minimumRange: 0,
    maximumRange: 4.8,
    activeMoveSpeed: 6.5,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
  {
    id: "blink-stalker-strike-v1",
    action: "blink-lunge",
    telegraphMs: 875,
    minimumTelegraphMs: 700,
    activeMs: 260,
    recoveryMs: 750,
    cooldownMs: 1_450,
    minimumRange: 2,
    maximumRange: 22,
    activeMoveSpeed: 12,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
  {
    id: "conductor-pulse-v1",
    action: "support-pulse",
    telegraphMs: 500,
    minimumTelegraphMs: 400,
    activeMs: 1,
    recoveryMs: 350,
    cooldownMs: 1_150,
    minimumRange: 0,
    maximumRange: 30,
    activeMoveSpeed: 0,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
  {
    id: "elite-redline-charge-v1",
    action: "melee-lunge",
    telegraphMs: 813,
    minimumTelegraphMs: 650,
    activeMs: 500,
    recoveryMs: 900,
    cooldownMs: 1_400,
    minimumRange: 3,
    maximumRange: 20,
    activeMoveSpeed: 19,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 0,
    repeatTelegraphMs: 500,
  },
  {
    id: "elite-twin-volley-v1",
    action: "projectile-volley",
    telegraphMs: 625,
    minimumTelegraphMs: 500,
    activeMs: 1,
    recoveryMs: 420,
    cooldownMs: 1_050,
    minimumRange: 4,
    maximumRange: 20,
    activeMoveSpeed: 0,
    projectileDefinitionId: STANDARD_ROUND_PROJECTILE_ID,
    volleyAnglesRadians: [-degrees(18), 0, degrees(18)],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
  {
    id: "elite-architect-barrier-v1",
    action: "deploy-barrier",
    telegraphMs: 700,
    minimumTelegraphMs: 600,
    activeMs: 1,
    recoveryMs: 500,
    cooldownMs: 1_700,
    minimumRange: 4,
    maximumRange: 22,
    activeMoveSpeed: 0,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 2,
    repeatTelegraphMs: null,
  },
  {
    id: "elite-fortress-sweep-v1",
    action: "melee-lunge",
    telegraphMs: 800,
    minimumTelegraphMs: 700,
    activeMs: 360,
    recoveryMs: 900,
    cooldownMs: 1_350,
    minimumRange: 0,
    maximumRange: 4.8,
    activeMoveSpeed: 6.5,
    projectileDefinitionId: null,
    volleyAnglesRadians: [],
    deploymentCount: 0,
    repeatTelegraphMs: null,
  },
]);
